package: ffmpeg
version: '2.0.0'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/ffmpeg

# Seiten
pages:
    mediapool/ffmpeg:
        title: 'Video-Konverter'
        perm: ffmpeg[]
        icon: rex-icon fa-video-camera

        subpages:
            main:
                title: 'translate:ffmpeg_main'
                perm: ffmpeg[]
            config:
                title: 'translate:ffmpeg_video_config'
                perm: ffmpeg[config]
                icon: rex-icon fa-wrench

default_config:
    command: 'ffmpeg -y -i INPUT -vcodec h264 -crf 23 -preset veryfast OUTPUT.mp4'
    poster_quality: 'jpeg_medium'
    trim_preset: 'veryfast'
    inherit_meta: '1'

requires:
    redaxo: '^5.10'
    packages:
        media_manager: '^2.0.1'
    php:
        version: '>=7.3'
        extensions: [gd, xml]

installer_ignore:
    - node_modules
    - .env
