package: ffmpeg
version: '3.2.2'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/

# Seiten
pages:
    mediapool/ffmpeg:
        title: 'Video-Tools'
        perm: ffmpeg[]
        icon: rex-icon fa-compress

        subpages:
            main:
                title: 'translate:ffmpeg_main'
                perm: ffmpeg[]
            trimmer:
                title: 'translate:ffmpeg_trimmer'
                perm: ffmpeg[]
                icon: rex-icon fa-cut
            info:
                title: 'translate:ffmpeg_info'
                perm: ffmpeg[]
                icon: rex-icon fa-info-circle
            help:
                title: 'translate:ffmpeg_help'
                perm: ffmpeg[]
                icon: rex-icon fa-question-circle
                subPath: README.md
            config:
                title: 'translate:ffmpeg_video_config'
                perm: ffmpeg[config]
                icon: rex-icon fa-wrench
default_config:
    command: 'ffmpeg -y -i INPUT -vcodec h264   OUTPUT.mp4'

requires:
    redaxo: '^5.18.1'
    packages:
        mediapool: '^2.14.0'
        media_manager: '^2.14.0'
    php:
        version: '>=8.1'
        extensions: [gd, xml]

conflicts:
    packages:
        videopreview: '*'

installer_ignore:
    - node_modules
    - .env
